#CI De Nível 01 - Disparo manual a partir de 1 clique

# Nome que vai aparecer la nas opções de pipe
name: 'Execução Manual'

# Triggers ou gatilhos de execução
  #gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:

  # descricao do job
  e2e-tests:

    # maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    # passo a passo das acoes do job
    steps:

      - uses: actions/checkout@v4

   # - uses: actions/setup-node@v4
   #   with:
   #     node-version:çts/*
   #   - name: Instalando Yarn
    #    run: npm install -g yarn

    #  - name: Instalando depedências
    #    run: yarn
      - name: instalando depedências
        run: npm install    
    
      - name: Testes E2E (end-to-end)
        run: npx cypress run

      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: cypress